# Why do we need Pytorch?

The problem with Numpy was that id did not run on GPUs so when Deep Learning came into the picture, GPUs became important for doing all the calculations required for DL. So pytorch is just like Numpy on a GPU with a lot of helper functions.

In [1]:
import torch

Let's get started with very basic operations using Pytorch.

In [2]:
x = torch.Tensor([5, 1])
y = torch.Tensor([2, 3])

z = x*y
print(z)

tensor([10.,  3.])


# What is a Pytorch Tensor?

What did we just do and what is a tensor? 
Answer (Using Pytorch Documentation): A PyTorch Tensor is basically the same as a numpy array: it does not know anything about deep learning or computational graphs or gradients, and is just a generic n-dimensional array to be used for arbitrary numeric computation.

The biggest difference between a numpy array and a PyTorch Tensor is that a PyTorch Tensor can run on either CPU or GPU. To run operations on the GPU, just cast the Tensor to a cuda datatype.

Let's move on to some basic operations that we can carry out using Pytorch

In [3]:
zeros_2_5 = torch.zeros([2,5])
print (zeros_2_5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
zeros_2_5.shape

torch.Size([2, 5])

In [5]:
rand_2_5 = torch.rand([2,5])
print(rand_2_5)

tensor([[0.5053, 0.0453, 0.5464, 0.9517, 0.6001],
        [0.8397, 0.0436, 0.0210, 0.1278, 0.2972]])


## Reshaping the tensor
Suppose we need to flatten a $2 \times 5$ pixel image, we can do it using 'view'. But remember to reassign

In [8]:
rand_1_10 = rand_2_5.view([1,10])
print(rand_1_10)

tensor([[0.5053, 0.0453, 0.5464, 0.9517, 0.6001, 0.8397, 0.0436, 0.0210, 0.1278,
         0.2972]])
